# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build App Files
        run: |
          sudo apt install --no-install-recommends wget esbuild -y
          wget -O pla-site-tool "https://github.com/kazam0180/portable-apps/releases/download/pla-site-tool-0.1.3/pla-site-tool_0.1.3-x86_64.AppImage"
          wget -O magick "https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-29/ImageMagick-7.1.2-29-gcc-x86_64.AppImage"
          chmod a+x magick
          ./magick --appimage-extract
          ls squashfs-root
          sudo cp -r squashfs-root/usr/* /usr/
          sudo chmod a+x /usr/bin/magick
          rm -rf magick squashfs-root

          [ ! -x ./pla-site-tool ] && chmod a+x ./pla-site-tool
          ./pla-site-tool 2>&1 | tee build-log.txt

          rm -f sitemap.xml
          [ ! -x ./gen_sitemap ] && chmod a+x ./gen_sitemap
          ./gen_sitemap public https://kazam0180.github.io/pla-site-testing/ 2>&1 | tee build-log.txt

          [ ! -x ./convert_icons ] && chmod a+x ./convert_icons
          ./convert_icons public 2>&1 | tee build-log.txt

          [ ! -x ./minify ] && chmod a+x ./minify
          ./minify public 2>&1 | tee build-log.txt

          cp -t public/ favicon.ico *.webp
          cp -r assets/fonts public/assets/
          cp -r casts public/
          cp -r am-gui public/
          cp -t public/ apps.html wiki.html sitemap.xml

          echo "site generated" | tee -a build-log.txt

      - name: Upload Build Log
        uses: actions/upload-artifact@v6
        with:
          name: build-log
          path: build-log.txt

      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
